apiVersion: v1
kind: Namespace
metadata:
  name: nexus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: singiattend-sa
  namespace: nexus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: singiattend-role
  namespace: nexus
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: singiattend-rb
  namespace: nexus
subjects:
  - kind: ServiceAccount
    name: singiattend-sa
roleRef:
  kind: Role
  name: singiattend-role
  apiGroup: rbac.authorization.k8s.io
---
# Persistent Volume for MongoDB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: nexus
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/mongodb
---
# PVC for MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: singiattend-mongo
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: singiattend-mongo
  template:
    metadata:
      labels:
        app: singiattend-mongo
    spec:
      containers:
        - name: singiattend-mongo
          image: nexus.markodojkic.qzz.io/docker-colima-local/singiattend-mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-storage
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "4"
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: nexus-credentials
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: singiattend-mongo
  namespace: nexus
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    app: singiattend-mongo
  type: ClusterIP
---
# ConfigMaps
apiVersion: v1
kind: ConfigMap
metadata:
  name: singiattend-fe-cm
  namespace: nexus
data:
  APP_CONTEXT_PATH: /teacher
  BE_SERVICE_NAME: singiattend-server.nexus.svc.cluster.local
  BE_APP_CONTEXT_PATH: /server
  BE_PORT: "62811"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: singiattend-be-cm
  namespace: nexus
data:
  APP_NAME: singiattend-server
  APP_CONTEXT_PATH: /server
  ALLOWED_ORIGINS: "http://singiattend-sp.nexus.svc.cluster.local:62814,http://singiattend-fe.nexus.svc.cluster.local:80,https://singiattend.k8s.markodojkic.local,https://singiattend.markodojkic.qzz.io"
  PORT: "62811"
  MONGO_HOST: singiattend-mongo.nexus.svc.cluster.local
  MONGO_PORT: "27017"
  TENANTS: |
    [
      {"tenantId":"SingidunumBG","db":"SingiAttend_BG"},
      {"tenantId":"SingidunumNS","db":"SingiAttend_NS"},
      {"tenantId":"SingidunumNIS","db":"SingiAttend_NIS"}
    ]
  IAM_SAML_RELAYING_PARTIES: |
    [
      {"metadataEndpoint":"http://keycloak.security.svc.cluster.local/realms/singiattend/protocol/saml/descriptor","host":"keycloak.k8s.markodojkic.local","isSSLEnabled":true,"entityId":"singiattend-local","wantAuthnRequestsSigned":true},
      {"metadataEndpoint":"http://keycloak.security.svc.cluster.local/realms/singiattend/protocol/saml/descriptor","host":"keycloak.markodojkic.qzz.io","isSSLEnabled":true,"entityId":"singiattend-cloudflare","wantAuthnRequestsSigned":true}
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: singiattend-sp-cm
  namespace: nexus
data:
  APP_CONTEXT_PATH: /student
  APP_NAME: singiattend-student-proxy
  KUBERNETES_NAMESPACE: nexus
  PORT: "62814"
  FEIGN_CLIENT_NAME: singiattend-server
  FEIGN_CLIENT_PATH: server
  FEIGN_CONTEXT_ID: singiattend-server-client
  IAM_SAML_RELAYING_PARTIES: |
    [
      {"metadataEndpoint":"http://keycloak.security.svc.cluster.local/realms/singiattend/protocol/saml/descriptor","host":"keycloak.k8s.markodojkic.local","isSSLEnabled":true,"entityId":"singiattend-student-local","wantAuthnRequestsSigned":true},
      {"metadataEndpoint":"http://keycloak.security.svc.cluster.local/realms/singiattend/protocol/saml/descriptor","host":"keycloak.markodojkic.qzz.io","isSSLEnabled":true,"entityId":"singiattend-student-cloudflare","wantAuthnRequestsSigned":true}
    ]
---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: backend-auth-secret
  namespace: nexus
type: Opaque
data:
  BACKEND_USERNAME: c2luZ2lhdHRlbmQtdXNlcg==
  BACKEND_PASSWORD: c2luZ2lhdHRlbmQtc3R1ZGVudF9zZXJ2ZXIyMDI1
---
apiVersion: v1
kind: Secret
metadata:
  name: fe-cloudflare-secret
  namespace: nexus
type: Opaque
data:
  CLOUDFLARE_SITE_KEY: <data_expunged>
  CLOUDFLARE_SECRET_KEY: <data_expunged>
---
apiVersion: v1
kind: Secret
metadata:
  name: be-ssl-secret
  namespace: nexus
type: Opaque
data:
  SSL_TRUST_STORE_PASSWORD: N15CcFVtNm1edGwjek5Odg==
  SSL_KEY_PASSWORD: c2luZ2lhdHRlbmQtc3R1ZGVudF9zZXJ2ZXIyMDI1
  SSL_KEY_STORE_PASSWORD: c2luZ2lhdHRlbmQtc3R1ZGVudF9zZXJ2ZXIyMDI1
---
apiVersion: v1
kind: Secret
metadata:
  name: sp-ssl-secret
  namespace: nexus
type: Opaque
data:
  SSL_TRUST_STORE_PASSWORD: N15CcFVtNm1edGwjek5Odg==
  SERVER_SSL_KEY_PASSWORD: c2luZ2lhdHRlbmQtc3R1ZGVudF9wcm94eTIwMjU=
  SERVER_SSL_KEY_STORE_PASSWORD: c2luZ2lhdHRlbmQtc3R1ZGVudF9wcm94eTIwMjU=
---
apiVersion: v1
kind: Secret
metadata:
  name: iam-truststore-secret
  namespace: nexus
type: Opaque
data:
  IAM_SSL_TRUSTSTORE_PASSWORD: VVBwNj1IRDkhLnokNWY5QA==
---
# FE Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: singiattend-fe
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: singiattend-fe
  template:
    metadata:
      labels:
        app: singiattend-fe
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: singiattend-appstack
          image: nexus.markodojkic.qzz.io/docker-colima-local/singiattend-appstack:latest
          ports:
            - containerPort: 80
              name: fe
          envFrom:
            - configMapRef:
                name: singiattend-fe-cm
            - secretRef:
                name: backend-auth-secret
            - secretRef:
                name: fe-cloudflare-secret
          readinessProbe:
            httpGet:
              path: /index.php?language=serbianCyrilic&page=login
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /index.php?language=serbianCyrilic&page=login
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "1"
              ephemeral-storage: "1Gi"
        - name: php-metrics
          image: nexus.markodojkic.qzz.io/docker-colima-local/php-metrics:latest
          ports:
            - containerPort: 9113
              name: metrics
          env:
            - name: TARGET_HOST
              value: singiattend-fe.nexus.svc.cluster.local
            - name: TARGET_PORT
              value: "80"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "1"
              ephemeral-storage: "1Gi"
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: nexus-credentials
---
# FE Service
apiVersion: v1
kind: Service
metadata:
  name: singiattend-fe
  namespace: nexus
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: singiattend-fe
  type: ClusterIP
---
# BE Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: singiattend-be
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: singiattend-be
  template:
    metadata:
      labels:
        app: singiattend-be
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "62811"
        prometheus.io/path: "/server/actuator/prometheus"
    spec:
      containers:
        - name: singiattend-server
          image: nexus.markodojkic.qzz.io/docker-colima-local/singiattend-server:latest
          ports:
            - containerPort: 62811
              name: be
          envFrom:
            - configMapRef:
                name: singiattend-be-cm
            - secretRef:
                name: be-ssl-secret
            - secretRef:
                name: iam-truststore-secret
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /server/actuator/health/readiness
              port: 62811
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /server/actuator/health/liveness
              port: 62811
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
              ephemeral-storage: "1Gi"
            limits:
              memory: "4Gi"
              cpu: "4"
              ephemeral-storage: "4Gi"
      serviceAccountName: singiattend-sa
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: nexus-credentials
---
# BE Service
apiVersion: v1
kind: Service
metadata:
  name: singiattend-server
  namespace: nexus
spec:
  ports:
    - name: https
      port: 62811
      targetPort: 62811
  selector:
    app: singiattend-be
  type: ClusterIP
---
# Student Proxy Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: singiattend-sp
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: singiattend-sp
  template:
    metadata:
      labels:
        app: singiattend-sp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "62814"
        prometheus.io/path: "/student/actuator/prometheus"
    spec:
      containers:
        - name: singiattend-student-proxy
          image: nexus.markodojkic.qzz.io/docker-colima-local/singiattend-student-proxy:latest
          ports:
            - containerPort: 62814
              name: sp
          envFrom:
            - configMapRef:
                name: singiattend-sp-cm
            - secretRef:
                name: sp-ssl-secret
            - secretRef:
                name: backend-auth-secret
            - secretRef:
                name: iam-truststore-secret
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /student/actuator/health/readiness
              port: 62814
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /student/actuator/health/liveness
              port: 62814
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
              ephemeral-storage: "1Gi"
            limits:
              memory: "4Gi"
              cpu: "4"
              ephemeral-storage: "4Gi"
      serviceAccountName: singiattend-sa
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: nexus-credentials
---
# Student Proxy Service
apiVersion: v1
kind: Service
metadata:
  name: singiattend-sp
  namespace: nexus
spec:
  ports:
    - name: https
      port: 62814
      targetPort: 62814
  selector:
    app: singiattend-sp
  type: ClusterIP
---
# Prometheus ServiceMonitor for FE metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: php-fe
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: singiattend-fe
  namespaceSelector:
    matchNames:
      - nexus
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
---
#Ingress for teacher
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: singiattend-teacher
  namespace: nexus
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - singiattend.k8s.markodojkic.local
      secretName: ingress-k8s-tls
  rules:
    - host: singiattend.k8s.markodojkic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: singiattend-fe
                port:
                  number: 80
    - host: singiattend.markodojkic.qzz.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: singiattend-fe
                port:
                  number: 80
---
#Ingress for student
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: singiattend-student
  namespace: nexus
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - singiattend.k8s.markodojkic.local
      secretName: ingress-k8s-tls
  rules:
    - host: singiattend.k8s.markodojkic.local
      http:
        paths:
          - path: /student
            pathType: Prefix
            backend:
              service:
                name: singiattend-sp
                port:
                  number: 62814
    - host: singiattend.markodojkic.qzz.io
      http:
        paths:
          - path: /student
            pathType: Prefix
            backend:
              service:
                name: singiattend-sp
                port:
                  number: 62814
---
#Ingress for singiattend-server (SAML related endpoints only)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: singiattend-teacher-saml
  namespace: nexus
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/iam(/|$)(.*) /server/iam/$2 break;
    nginx.ingress.kubernetes.io/use-forwarded-headers: 'true'
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - singiattend.k8s.markodojkic.local
      secretName: ingress-k8s-tls
  rules:
    - host: singiattend.k8s.markodojkic.local
      http:
        paths:
          - path: /iam(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: singiattend-server
                port:
                  number: 62811
          - path: /server/iam(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: singiattend-server
                port:
                  number: 62811
    - host: singiattend.markodojkic.qzz.io
      http:
        paths:
          - path: /iam(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: singiattend-server
                port:
                  number: 62811
          - path: /server/iam(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: singiattend-server
                port:
                  number: 62811