spring:
  application:
    name: ${APP_NAME:SingiAttend-Server}
  main:
    allow-circular-references: true
    cloud-platform: kubernetes
  cloud:
    kubernetes:
      discovery:
        enabled: true
      client:
        namespace: ${KUBERNETES_NAMESPACE:default}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      cors:
        allowed-origins: "*"
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      version: ${project.version}

server:
  servlet:
    context-path: ${APP_CONTEXT_PATH:}
  port: ${PORT:62812}
  http2:
    enabled: true
  ssl:
    key-store: classpath:ssl_keystore-signed.p12
    key-store-type: PKCS12
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-password: ${SERVER_SSL_KEY_PASSWORD}
    enabled: true
    enabled-protocols: TLSv1.2,TLSv1.3
    protocol: TLS

tenants: ${TENANTS}
mongoHost: ${MONGO_HOST:localhost:27017}
allowed-origins: ${ALLOWED_ORIGINS}