spring:
  application:
    name: ${PROXY_APP_NAME:SingiAttend-Student_Proxy}
  cloud:
    kubernetes:
      discovery:
        enabled: true
      client:
        namespace: ${KUBERNETES_NAMESPACE:default}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      version: ${project.version}

server:
  port: ${PROXY_PORT:62814}
  http2:
    enabled: true
  ssl:
    key-store: classpath:ssl_keystore-signed.p12
    key-store-type: PKCS12
    key-store-password: ${PROXY_SERVER_SSL_KEY_STORE_PASSWORD}
    key-password: ${PROXY_SERVER_SSL_KEY_PASSWORD}
    enabled: true
    enabled-protocols: TLSv1.2,TLSv1.3
    protocol: TLS

feign:
  singiattend:
    server_client: ${PROXY_FEIGN_SINGIATTEND_CLIENT:singiattend-server}
